nav:
  Home: /
  Writing: /archives/
  Projects: http://github.com/edouardmenayde

projects_url: http://github.com/edouardmenayde

customize:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo-min.jpg
    social_links:
        github: https://github.com/edouardmenayde
        linkedin: https://www.linkedin.com/in/edouard-menayde-b17626135
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss:

# Plugins
plugins:
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        image: /images/logo.jpg
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
